from __future__ import annotations

MIB_NODE_SEEDS = [
    {
        "oid": "1.3.6.1.4.1.42669.1.1.0.1",
        "name": "almchg",
        "category": "trap",
        "access": "notify",
        "data_type": "notification",
        "description": "告警变更通知，告警产生、消除、级别变化时上报。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.1.0.5",
        "name": "performance",
        "category": "trap",
        "access": "notify",
        "data_type": "notification",
        "description": "性能数据上报通知。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.1",
        "name": "almChgIdx",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "string",
        "description": "索引，格式 ifindex.almid。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.2",
        "name": "almChgObj",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "string",
        "description": "告警对象，端口或资源标识。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.3",
        "name": "almChgAid",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "string",
        "description": "告警 ID。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.4",
        "name": "almChgLvl",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "integer",
        "description": "告警级别。",
        "enum_name": "EALARMLVL",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.5",
        "name": "almChgTime",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "string",
        "description": "告警发生时间原始值。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.6",
        "name": "almChgStat",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "integer",
        "description": "告警状态。",
        "enum_name": "EALARMSTAT",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.7",
        "name": "almChgObjDesc",
        "category": "trap_field",
        "access": "read-only",
        "data_type": "string",
        "description": "告警对象描述。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.5.1.1",
        "name": "perIdx",
        "category": "performance",
        "access": "read-only",
        "data_type": "string",
        "description": "性能索引，格式 time.ordinal。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.5.1.2",
        "name": "perDesc",
        "category": "performance",
        "access": "read-only",
        "data_type": "string",
        "description": "性能字段字符串 objid,perid,val,flag,nms,vneid。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "oid": "1.3.6.1.4.1.42669.1.2.200",
        "name": "almGetall",
        "category": "manual_action",
        "access": "read-only",
        "data_type": "trigger",
        "description": "手动读取此 OID 可触发设备重新上报当前所有告警。",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.1",
        "name": "apsEn",
        "category": "aps",
        "access": "read-write",
        "data_type": "integer",
        "description": "APS 使能。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.2",
        "name": "apsWorkPort",
        "category": "aps",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 APS 工作口。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.3",
        "name": "apsPrtPort",
        "category": "aps",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 APS 保护口。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.4",
        "name": "apsRevertive",
        "category": "aps",
        "access": "read-write",
        "data_type": "integer",
        "description": "APS 恢复模式。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.5",
        "name": "apsWtrTime",
        "category": "aps",
        "access": "read-write",
        "data_type": "integer",
        "description": "WTR 时间，单位秒。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.6",
        "name": "apsHoldoffTime",
        "category": "aps",
        "access": "read-write",
        "data_type": "integer",
        "description": "保护倒换延迟，单位毫秒。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.7",
        "name": "apsBwsvThrd",
        "category": "aps",
        "access": "read-write",
        "data_type": "integer",
        "description": "带宽保护倒换阈值。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.8",
        "name": "apsSwCmd",
        "category": "aps",
        "access": "read-write",
        "data_type": "integer",
        "description": "APS 手动或强制倒换命令，第一版只展示不下发。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.9",
        "name": "apsActive",
        "category": "aps",
        "access": "read-only",
        "data_type": "string",
        "description": "当前活跃侧。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.2.10",
        "name": "apsStat",
        "category": "aps",
        "access": "read-only",
        "data_type": "integer",
        "description": "APS 状态机状态。",
        "enum_name": "EAPSSTATE",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.3.1",
        "name": "dfpEn",
        "category": "dfp",
        "access": "read-write",
        "data_type": "integer",
        "description": "DFP 使能。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.3.2",
        "name": "dfpPeer",
        "category": "dfp",
        "access": "read-only",
        "data_type": "string",
        "description": "DFP 对端设备 IPv4 地址。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.3.3",
        "name": "dfpSwCmd",
        "category": "dfp",
        "access": "read-write",
        "data_type": "integer",
        "description": "DFP 倒换命令，第一版只展示不下发。",
        "enum_name": "EDFPCMD",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "oid": "1.3.6.1.4.1.42669.3.4",
        "name": "dfpActive",
        "category": "dfp",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 DFP 活跃侧。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
]

MIB_ENUM_SEEDS = [
    ("EALARMLVL", 0, "cleared", "告警消除"),
    ("EALARMLVL", 1, "indeterminate", "不确定"),
    ("EALARMLVL", 2, "warning", "警告"),
    ("EALARMLVL", 3, "minor", "次要"),
    ("EALARMLVL", 4, "major", "主要"),
    ("EALARMLVL", 5, "critical", "紧急"),
    ("EALARMSTAT", 42, "change", "告警变化"),
    ("EALARMSTAT", 43, "report", "告警上报"),
    ("EALARMSTAT", 45, "close", "告警关闭"),
    ("EAPSSTATE", 0, "normal", "正常状态"),
    ("EAPSSTATE", 1, "holdW", "保持工作口"),
    ("EAPSSTATE", 2, "holdP", "保持保护口"),
    ("EAPSSTATE", 3, "protectW", "保护倒换至工作口"),
    ("EAPSSTATE", 4, "protectP", "保护倒换至保护口"),
    ("EAPSSTATE", 5, "wtrW", "WTR等待，工作口"),
    ("EAPSSTATE", 6, "wtrP", "WTR等待，保护口"),
    ("EAPSSTATE", 7, "forceW", "强制切至工作口"),
    ("EAPSSTATE", 8, "forceP", "强制切至保护口"),
    ("EAPSSTATE", 15, "disable", "APS禁用"),
    ("EDFPCMD", 0, "normal", "无倒换命令"),
    ("EDFPCMD", 1, "self", "强制本端激活"),
    ("EDFPCMD", 2, "peer", "强制对端激活"),
]

_CRITICAL_ALARMS = [
    "Power1_Fail",
    "Power2_Fail",
    "HighTemp",
    "LowTemp",
    "PKG_FAIL",
    "LOS",
    "LsrOffline",
    "HighSysMem",
    "HighRootfs",
    "HighAppdisk",
    "PKG_NOTREADY",
]

_MAJOR_ALARMS = [
    "FAN1_FAIL",
    "FAN2_FAIL",
    "FAN3_FAIL",
    "FAN4_FAIL",
]

_WARNING_ALARMS = [
    "LB_15L",
    "LB_24L",
    "LB_15H",
    "LB_24H",
    "LT_15L",
    "LT_24L",
    "LT_15H",
    "LT_24H",
    "IOP_15L",
    "IOP_24L",
    "IOP_15H",
    "IOP_24H",
    "OOP_15L",
    "OOP_24L",
    "OOP_15H",
    "OOP_24H",
    "RAM_15H",
    "RAM_24H",
    "CPU_15H",
    "CPU_24H",
]

ALARM_RULE_SEEDS = [
    {
        "alarm_id": alarm_id,
        "default_severity": "critical",
        "should_create_active": True,
        "should_popup": True,
        "category": "critical",
        "description": alarm_id,
    }
    for alarm_id in _CRITICAL_ALARMS
] + [
    {
        "alarm_id": alarm_id,
        "default_severity": "major",
        "should_create_active": True,
        "should_popup": True,
        "category": "major",
        "description": alarm_id,
    }
    for alarm_id in _MAJOR_ALARMS
] + [
    {
        "alarm_id": alarm_id,
        "default_severity": "warning",
        "should_create_active": True,
        "should_popup": False,
        "category": "warning",
        "description": alarm_id,
    }
    for alarm_id in _WARNING_ALARMS
]
