from __future__ import annotations

DEFAULT_PROFILE_CODE = "bohui_rx10"

DEVICE_PROFILE_SEEDS = [
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "vendor": "博汇",
        "model": "RX10",
        "category": "中继器",
        "parser_key": DEFAULT_PROFILE_CODE,
        "description": "博汇 RX10 中继器默认模板。",
        "is_builtin": True,
    }
]

MIB_NODE_SEEDS = [
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.1.0.1",
        "name": "almchg",
        "name_zh": "告警变更 Trap",
        "category": "trap",
        "category_zh": "Trap",
        "access": "notify",
        "data_type": "notification",
        "description": "告警变更通知，告警产生、消除、级别变化时上报。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.1.0.5",
        "name": "performance",
        "name_zh": "性能上报 Trap",
        "category": "trap",
        "category_zh": "Trap",
        "access": "notify",
        "data_type": "notification",
        "description": "性能数据上报通知。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.1",
        "name": "almChgIdx",
        "name_zh": "告警索引",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "string",
        "description": "索引，格式 ifindex.almid。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.2",
        "name": "almChgObj",
        "name_zh": "告警对象",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "string",
        "description": "告警对象，端口或资源标识。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.3",
        "name": "almChgAid",
        "name_zh": "告警 ID",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "string",
        "description": "告警 ID。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.4",
        "name": "almChgLvl",
        "name_zh": "告警级别",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "integer",
        "description": "告警级别。",
        "enum_name": "EALARMLVL",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.5",
        "name": "almChgTime",
        "name_zh": "设备告警时间",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "string",
        "description": "设备上报告警时间原始值。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.6",
        "name": "almChgStat",
        "name_zh": "告警状态",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "integer",
        "description": "告警状态。",
        "enum_name": "EALARMSTAT",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.1.1.7",
        "name": "almChgObjDesc",
        "name_zh": "告警对象描述",
        "category": "trap_field",
        "category_zh": "Trap字段",
        "access": "read-only",
        "data_type": "string",
        "description": "告警对象描述。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.5.1.1",
        "name": "perIdx",
        "name_zh": "性能索引",
        "category": "performance",
        "category_zh": "性能",
        "access": "read-only",
        "data_type": "string",
        "description": "性能索引，格式 time.ordinal。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.5.1.2",
        "name": "perDesc",
        "name_zh": "性能描述",
        "category": "performance",
        "category_zh": "性能",
        "access": "read-only",
        "data_type": "string",
        "description": "性能字符串，格式 objid,perid,val,flag,nms,vneid。",
        "is_pollable": False,
        "is_trap_field": True,
        "is_set_reserved": False,
        "scalar_suffix_zero": False,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.1.2.200",
        "name": "almGetall",
        "name_zh": "触发全量告警上报",
        "category": "manual_action",
        "category_zh": "手动动作",
        "access": "read-only",
        "data_type": "trigger",
        "description": "读取该 OID 可触发设备重新上报当前所有告警。",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.1",
        "name": "apsEn",
        "name_zh": "APS 使能",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-write",
        "data_type": "integer",
        "description": "APS 使能状态。",
        "enum_name": "ESWITCH",
        "unit": "",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 10,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.2",
        "name": "apsWorkPort",
        "name_zh": "APS 工作口",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 APS 工作口。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 20,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.3",
        "name": "apsPrtPort",
        "name_zh": "APS 保护口",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 APS 保护口。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 30,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.4",
        "name": "apsRevertive",
        "name_zh": "APS 恢复模式",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-write",
        "data_type": "integer",
        "description": "APS 恢复模式。",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.5",
        "name": "apsWtrTime",
        "name_zh": "APS WTR 时间",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-write",
        "data_type": "integer",
        "description": "WTR 时间，单位秒。",
        "unit": "秒",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.6",
        "name": "apsHoldoffTime",
        "name_zh": "APS 保护倒换延迟",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-write",
        "data_type": "integer",
        "description": "保护倒换延迟，单位毫秒。",
        "unit": "毫秒",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.7",
        "name": "apsBwsvThrd",
        "name_zh": "APS 带宽保护阈值",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-write",
        "data_type": "integer",
        "description": "带宽保护倒换阈值。",
        "unit": "%",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.8",
        "name": "apsSwCmd",
        "name_zh": "APS 倒换命令",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-write",
        "data_type": "integer",
        "description": "APS 手动或强制倒换命令，第一版只展示不下发。",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.9",
        "name": "apsActive",
        "name_zh": "APS 当前活跃侧",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 APS 活跃侧。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 40,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.10",
        "name": "apsStat",
        "name_zh": "APS 状态机状态",
        "category": "aps",
        "category_zh": "APS",
        "access": "read-only",
        "data_type": "integer",
        "description": "APS 状态机当前状态。",
        "enum_name": "EAPSSTATE",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 50,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.1",
        "name": "dfpEn",
        "name_zh": "DFP 使能",
        "category": "dfp",
        "category_zh": "DFP",
        "access": "read-write",
        "data_type": "integer",
        "description": "DFP 使能。",
        "enum_name": "ESWITCH",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 60,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.2",
        "name": "dfpPeer",
        "name_zh": "DFP 对端地址",
        "category": "dfp",
        "category_zh": "DFP",
        "access": "read-only",
        "data_type": "string",
        "description": "DFP 对端设备 IPv4 地址。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 70,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.3",
        "name": "dfpSwCmd",
        "name_zh": "DFP 倒换命令",
        "category": "dfp",
        "category_zh": "DFP",
        "access": "read-write",
        "data_type": "integer",
        "description": "DFP 倒换命令，第一版只展示不下发。",
        "enum_name": "EDFPCMD",
        "is_pollable": False,
        "is_trap_field": False,
        "is_set_reserved": True,
        "scalar_suffix_zero": True,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.4",
        "name": "dfpActive",
        "name_zh": "DFP 当前活跃侧",
        "category": "dfp",
        "category_zh": "DFP",
        "access": "read-only",
        "data_type": "string",
        "description": "当前 DFP 活跃侧。",
        "is_pollable": True,
        "is_trap_field": False,
        "is_set_reserved": False,
        "scalar_suffix_zero": True,
        "overview_order": 80,
    },
]

MIB_ENUM_SEEDS = [
    (DEFAULT_PROFILE_CODE, "ESWITCH", 0, "disable", "禁用"),
    (DEFAULT_PROFILE_CODE, "ESWITCH", 1, "enable", "启用"),
    (DEFAULT_PROFILE_CODE, "EALARMLVL", 0, "cleared", "告警清除"),
    (DEFAULT_PROFILE_CODE, "EALARMLVL", 1, "indeterminate", "不确定"),
    (DEFAULT_PROFILE_CODE, "EALARMLVL", 2, "warning", "警告"),
    (DEFAULT_PROFILE_CODE, "EALARMLVL", 3, "minor", "次要"),
    (DEFAULT_PROFILE_CODE, "EALARMLVL", 4, "major", "主要"),
    (DEFAULT_PROFILE_CODE, "EALARMLVL", 5, "critical", "紧急"),
    (DEFAULT_PROFILE_CODE, "EALARMSTAT", 42, "change", "告警变化"),
    (DEFAULT_PROFILE_CODE, "EALARMSTAT", 43, "report", "告警上报"),
    (DEFAULT_PROFILE_CODE, "EALARMSTAT", 45, "close", "告警关闭"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 0, "normal", "正常状态"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 1, "holdW", "保持工作口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 2, "holdP", "保持保护口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 3, "protectW", "保护倒换至工作口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 4, "protectP", "保护倒换至保护口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 5, "wtrW", "WTR等待，工作口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 6, "wtrP", "WTR等待，保护口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 7, "forceW", "强制切至工作口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 8, "forceP", "强制切至保护口"),
    (DEFAULT_PROFILE_CODE, "EAPSSTATE", 15, "disable", "APS禁用"),
    (DEFAULT_PROFILE_CODE, "EDFPCMD", 0, "normal", "无倒换命令"),
    (DEFAULT_PROFILE_CODE, "EDFPCMD", 1, "self", "强制本端激活"),
    (DEFAULT_PROFILE_CODE, "EDFPCMD", 2, "peer", "强制对端激活"),
]

POLLING_STRATEGY_SEEDS = [
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.1",
        "node_name": "apsEn",
        "node_name_zh": "APS 使能",
        "category": "aps",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": False,
        "show_in_device_card": False,
        "judge_type": "enum_equals",
        "expected_value_text": "1",
        "expected_values_json": ["1", "enable"],
        "health_on_mismatch": "warning",
        "notes": "建议使能状态为 1 / enable。",
        "display_order": 10,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.2",
        "node_name": "apsWorkPort",
        "node_name_zh": "APS 工作口",
        "category": "aps",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": False,
        "show_in_device_card": False,
        "judge_type": None,
        "health_on_mismatch": None,
        "notes": "只展示，不做正常判断。",
        "display_order": 20,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.3",
        "node_name": "apsPrtPort",
        "node_name_zh": "APS 保护口",
        "category": "aps",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": False,
        "show_in_device_card": False,
        "judge_type": None,
        "health_on_mismatch": None,
        "notes": "只展示，不做正常判断。",
        "display_order": 30,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.9",
        "node_name": "apsActive",
        "node_name_zh": "APS 当前活跃侧",
        "category": "aps",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": True,
        "show_in_device_card": True,
        "judge_type": None,
        "health_on_mismatch": None,
        "notes": "仅在总览与详情展示当前活跃侧。",
        "display_order": 40,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.2.10",
        "node_name": "apsStat",
        "node_name_zh": "APS 状态机状态",
        "category": "aps",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": True,
        "show_in_device_card": True,
        "judge_type": "enum_equals",
        "expected_value_text": "normal",
        "expected_values_json": ["0", "normal"],
        "health_on_mismatch": "warning",
        "notes": "默认以 normal/0 视为正常。",
        "display_order": 50,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.1",
        "node_name": "dfpEn",
        "node_name_zh": "DFP 使能",
        "category": "dfp",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": False,
        "show_in_device_card": False,
        "judge_type": "enum_equals",
        "expected_value_text": "1",
        "expected_values_json": ["1", "enable"],
        "health_on_mismatch": "warning",
        "notes": "建议使能状态为 1 / enable。",
        "display_order": 60,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.2",
        "node_name": "dfpPeer",
        "node_name_zh": "DFP 对端地址",
        "category": "dfp",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": False,
        "show_in_device_card": False,
        "judge_type": None,
        "health_on_mismatch": None,
        "notes": "只展示，不做正常判断。",
        "display_order": 70,
    },
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "oid": "1.3.6.1.4.1.42669.3.4",
        "node_name": "dfpActive",
        "node_name_zh": "DFP 当前活跃侧",
        "category": "dfp",
        "poll_interval_seconds": 60,
        "is_enabled": True,
        "save_history": True,
        "show_in_overview": True,
        "show_in_device_card": True,
        "judge_type": None,
        "health_on_mismatch": None,
        "notes": "仅展示，不做正常判断。",
        "display_order": 80,
    },
]

_CRITICAL_ALARMS = [
    "Power1_Fail",
    "Power2_Fail",
    "HighTemp",
    "LowTemp",
    "PKG_FAIL",
    "LOS",
    "LsrOffline",
    "HighSysMem",
    "HighRootfs",
    "HighAppdisk",
    "PKG_NOTREADY",
]

_MAJOR_ALARMS = [
    "FAN1_FAIL",
    "FAN2_FAIL",
    "FAN3_FAIL",
    "FAN4_FAIL",
]

_WARNING_ALARMS = [
    "LB_15L",
    "LB_24L",
    "LB_15H",
    "LB_24H",
    "LT_15L",
    "LT_24L",
    "LT_15H",
    "LT_24H",
    "IOP_15L",
    "IOP_24L",
    "IOP_15H",
    "IOP_24H",
    "OOP_15L",
    "OOP_24L",
    "OOP_15H",
    "OOP_24H",
    "RAM_15H",
    "RAM_24H",
    "CPU_15H",
    "CPU_24H",
]

ALARM_RULE_SEEDS = [
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "alarm_id": alarm_id,
        "default_severity": "critical",
        "should_create_active": True,
        "should_popup": True,
        "category": "critical",
        "description": alarm_id,
    }
    for alarm_id in _CRITICAL_ALARMS
] + [
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "alarm_id": alarm_id,
        "default_severity": "major",
        "should_create_active": True,
        "should_popup": True,
        "category": "major",
        "description": alarm_id,
    }
    for alarm_id in _MAJOR_ALARMS
] + [
    {
        "profile_code": DEFAULT_PROFILE_CODE,
        "alarm_id": alarm_id,
        "default_severity": "warning",
        "should_create_active": True,
        "should_popup": False,
        "category": "warning",
        "description": alarm_id,
    }
    for alarm_id in _WARNING_ALARMS
]
